/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dao;

import entities.Article;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author Elisa Bothy
 */
public class ArticleDao {
    Connection connection;

    public ArticleDao() {
        connection = MariadbConnection.getInstance();
    }
    
    public Article read(int id) {
        Article obj = null;
        String sql = "SELECT * FROM article WHERE id=?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, id);//le premier ? prend la valeur id 
            // que j'ai mis en paramètre
            ResultSet rs = pstmt.executeQuery();
            if (rs.first()){
                obj = new Article();
                obj.setId(rs.getInt("id"));
                obj.setSubject(rs.getString("subject"));
                obj.setContent(rs.getString("content"));
                obj.setCreated(rs.getDate("created"));
                obj.setAuthor(rs.getInt("author"));
            }
        } catch (SQLException ex) {
            System.out.println("Erreur lors de la lecture :" + ex.getMessage());
        }
       return obj;
    }
    
    public void create(Article obj){
        String sql = "INSERT INTO article (subject, content, created, author) " + "VALUES (?, ?, ?, ?)";
        try {
            PreparedStatement pstmt = connection
                    .prepareStatement(
                            sql,
                            PreparedStatement.RETURN_GENERATED_KEYS
                    );
            pstmt.setString(1, obj.getSubject());
            pstmt.setString(2, obj.getContent());
            pstmt.setDate(3, obj.getCreated());
            pstmt.setInt(4, obj.getAuthor());
            int nbLines = pstmt.executeUpdate();
            if(nbLines == 1){
                ResultSet autoGeneratedKeys = pstmt.getGeneratedKeys();
                autoGeneratedKeys.first();
                int id = autoGeneratedKeys.getInt(1);
                obj.setId(id);
            }
        } catch (SQLException ex) {
            System.out.println("Erreur lors de l'insertion :" + ex.getMessage());
        }
    }
  
    public void update (Article obj){
        String sql ="UPDATE article SET subject=?, content=?, created=?, author=? " + "WHERE id=?";
        
        PreparedStatement pstmt;
        try {
            pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, obj.getSubject());
            pstmt.setString(2, obj.getContent());
            pstmt.setDate(3, obj.getCreated());
            pstmt.setInt(4, obj.getAuthor());
            pstmt.setLong(5, obj.getId());
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            System.out.println("Erreur lors de l'update :" + ex.getMessage());
        }
        
    }
    
    public void delete(Integer id){
        String sql = "DELETE FROM article WHERE id=?";
        try {
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setInt(1, id);
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            System.out.println("Erreur lors du delete :" + ex.getMessage());
        }
    }
    
    public int count(){
        int count = 0;
        String sql = "SELECT COUNT(*) AS c FROM article";
        try {
            PreparedStatement pstmt = connection.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            if(rs.first()){
                count = rs.getInt("c");
            }
        } catch (SQLException ex) {
            System.out.println("Erreur lors du comptage :" + ex.getMessage());
        }
        return count;
    }
    
    public Collection<Article> list(){
        ArrayList<Article> list = new ArrayList<>();
        String sql = "SELECT * FROM article";
        try {
            PreparedStatement pstmt = connection.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next()){
                Article a = new Article();
                a.setId(rs.getInt("id"));
                a.setSubject(rs.getString("subject"));
                a.setContent(rs.getString("content"));
                a.setCreated(rs.getDate("created"));
                a.setAuthor(rs.getInt("author"));
                list.add(a);
            }
        } catch (SQLException ex) {
            System.out.println("Erreur lors du listage :" + ex.getMessage());
        }
        return list;
    }
}
